# Desktop colour theme for the cbox i3/Hyprland desktop.
#
# `my.desktop.theme` selects one of configs/desktop-themes/<name>.nix. Each app
# loads its colours from a fixed-name file rendered here, so switching themes is
# a host option change plus `home-manager switch`:
#   Waybar     ~/.config/waybar/theme.css           (@import from style.css)
#   Hyprland   ~/.config/hypr/desktop-theme.lua     (dofile from hyprland.lua)
#   hyprlock   ~/.config/hypr/hyprlock-theme.conf   (source from hyprlock.conf)
#   rofi       ~/.config/rofi/themes/desktop.rasi   (configs/rofi/themes/<name>.rasi)
#   Ghostty    ~/.config/ghostty/themes/desktop     (configs/ghostty/themes/<name>)
# dunst reads `my.desktop.palette` directly.
{ config, lib, dotfiles, ... }:
let
  themes = [ "solid-gold" "sourcerer" ];
  theme = config.my.desktop.theme;
  p = config.my.desktop.palette;
in
{
  options.my.desktop = {
    theme = lib.mkOption {
      type = lib.types.enum themes;
      default = "solid-gold";
      description = "Desktop colour theme; one of configs/desktop-themes/<name>.nix.";
    };

    palette = lib.mkOption {
      type = lib.types.attrsOf lib.types.str;
      readOnly = true;
      description = "Hex colours (without '#') of the selected desktop theme.";
    };
  };

  config = {
    my.desktop.palette = import (dotfiles + "/configs/desktop-themes/${theme}.nix");

    xdg.configFile."waybar/theme.css".text = ''
      /* Generated by nix/modules/desktop-theme.nix: ${theme} */
      @define-color background #${p.bg};
      @define-color background-alt #${p.bgAlt};
      @define-color edge #${p.edge};
      @define-color foreground #${p.fg};
      @define-color muted #${p.muted};
      @define-color accent #${p.accent};
      @define-color accent-dim #${p.accentDim};
      @define-color urgent #${p.urgent};
    '';

    xdg.configFile."hypr/desktop-theme.lua".text = ''
      -- Generated by nix/modules/desktop-theme.nix: ${theme}
      return {
          bg        = "rgb(${p.bg})",
          bgAlt     = "rgb(${p.bgAlt})",
          edge      = "rgb(${p.edge})",
          fg        = "rgb(${p.fg})",
          muted     = "rgb(${p.muted})",
          accent    = "rgb(${p.accent})",
          accentDim = "rgb(${p.accentDim})",
          urgent    = "rgb(${p.urgent})",
      }
    '';

    xdg.configFile."hypr/hyprlock-theme.conf".text = ''
      # Generated by nix/modules/desktop-theme.nix: ${theme}
      $bg = rgb(${p.bg})
      $bgAlt = rgb(${p.bgAlt})
      $edge = rgb(${p.edge})
      $fg = rgb(${p.fg})
      $muted = rgb(${p.muted})
      $accent = rgb(${p.accent})
      $accentDim = rgb(${p.accentDim})
      $urgent = rgb(${p.urgent})
    '';

    xdg.configFile."rofi/themes/desktop.rasi".source =
      dotfiles + "/configs/rofi/themes/${theme}.rasi";

    xdg.configFile."ghostty/themes/desktop".source =
      dotfiles + "/configs/ghostty/themes/${theme}";
  };
}
